
modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory
license = "${mod_license}"

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://modrinth.com/mod/create-wellss" #optional
logoFile="logo.png" #optional
#credits="" #optional
authors = "${mod_authors}" #optional
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]] #optional
modId = "neoforge" #mandatory
type = "required" #mandatory
versionRange = "${neo_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"


[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId="create"
mandatory=true
versionRange="[6.0.6,6.1.0)"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="jei"
mandatory=false
versionRange="[19.8.2.99,)"
ordering="NONE"
side="BOTH"
